### ISSUE TITLE
newLine

### ISSUE THREAD

**Issue by piranna** [websockets/wscat#12]
wscat is not sending `\n` at the end of the lines. Add an option so all the input is send, including the new lines.

**Comment by nwwells** [comment]
that's an interesting use case, though I'm not sure it's a common one. Can you explain a bit why you would want this?

**Comment by piranna** [comment]
Don't remember my exact use case, but it was related to something like sending text chunks or piping files on stdin. This way they can be fetch exact copies on the other end, otherwise they will get corrupted.

**Comment by nwwells** [comment]
OK. I'm going to close this and say it will be fixed when we implement the `--raw` option.

**Comment by bfreis** [comment]
I recently just needed the same feature. Use case: I'm using a websocket proxy to a text-based TCP service that understands commands ending with `\n`.

I couldn't find the `--raw` option. Is there an alternative today?

Thanks
Bruno

**Comment by samholmes** [comment]
Some JSON-RPC services over WebSockets will wait for newlines before processing the JSON. Perhaps supporting entering `\n` into your message with an escape character `\` could be added?
