### ISSUE TITLE
command not found: wscat

### ISSUE THREAD

**Issue by lobstaboy** [websockets/wscat#124]
I installed wscat using the -g, but when I try to run anything, such as wscat -V, it gives me the error:
command not found: wscat

**Comment by lpinca** [comment]
This is not a wscat issue, it is very likely that any other CLI installed -g does not work in your environment.

**Comment by lpinca** [comment]
Try to run `npm bin -g` and add that directory to your `PATH`.

**Comment by lobstaboy** [comment]
Woohoo! Thank you, it worked. I also got a permission denied error, which I fixed from [here](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally#reinstall-npm-with-a-node-version-manager).

**Comment by lpinca** [comment]
Ok, closing then.
