### ISSUE TITLE
Error reporting: SyntaxError: Unexpected token 

### ISSUE THREAD

**Issue by wushuaiping** [websockets/wscat#125]
![image](https://user-images.githubusercontent.com/26813459/88483853-338e4b80-cf9d-11ea-8c2f-a845d32a6895.png)

**Comment by wushuaiping** [comment]
![image](https://user-images.githubusercontent.com/26813459/88483908-77815080-cf9d-11ea-90ab-5990e63cf852.png)

**Comment by lpinca** [comment]
You need Node.js >= 8.3.0

**Comment by wushuaiping** [comment]
> You need Node.js >= 8.3.0

thansk
