### ISSUE TITLE
error: Server sent a subprotocol but none was requested

### ISSUE THREAD

**Issue by mmm286** [websockets/wscat#127]
Hi,
I'm trying to connect with wss but it gives me this error:

```
wscat -n -c "wss://mongooseimprotool-prod.wallapop.com/ws-xmpp"
error: Server sent a subprotocol but none was requested
```
Any help? Thanks

**Comment by lpinca** [comment]
As the error message says the server sent a subprotocol in the handshake response but the client did not request one. This is not allowed by the WebSocket protocol.

You can use the `-s` option to specify a subprotocol.
