### ISSUE TITLE
Blue is too dark

### ISSUE THREAD

**Issue by Ming-Tang** [websockets/wscat#15]
I'm using wscat in a terminal with black background, and when blue is used, I can't see the text. In Vim, I can do set bg=dark to make the text colors lighter. There should be a way to change or disable the colors.

**Comment by markwillis75** [comment]
It's not an ideal solution, but it's possible to edit the /npm/node_modules/wscat/bin/wscat file to use the colours you wish.

Locate the .on('message'...) conditional and change the color from Console.Colors.Blue to something more suitable.  Select from the existing colors defined in the Console.Colors array, or add new element to the array and use that.

**Comment by eaded110** [comment]
comment on issue

**Comment by genetique-techno** [comment]
Yes, yes it is...

**Comment by nwwells** [comment]
I'd be happy to review a PR for a `--no-color` option. `--raw` is also under consideration for #2 and #18, which would also solve this, but no reason we couldn't do both.
