### ISSUE TITLE
wscat node module not connected

### ISSUE THREAD

**Issue by jaskaran87** [websockets/wscat#23]
i have install node npm after that install wscat. I try to connect it with localhost but it is not working.

// with localhost

wscat -c ws://localhost:8000 
wscat -c ws://0.0.0.0:8000  

// with local ip address

wscat -c ws://192.168.1.159:8000
wscat -c ws://127.0.0.1:8000

Geting same error

error: Error: connect ECONNREFUSED 127.0.0.1:8000

get same error

/var/www/html/index.js

var WebSocketServer = require('/usr/local/lib/node_modules/wscat').Server,
wss = new WebSocketServer({ port: 8888 });

wss.on('connection', function (connection) {
    console.log("User connected");
    connection.on('message', function (message) {
        console.log("Got message:", message);
    });
    connection.send('Hello World');
});

**Comment by JacksonTian** [comment]
you should use port 8888 like `wscat -c ws://localhost:8888`.
