### ISSUE TITLE
wscat should allow specifying a client certificate

### ISSUE THREAD

**Issue by nwwells** [websockets/wscat#25]
See websockets/ws#882

**Comment by lpinca** [comment]
https://github.com/websockets/wscat/pull/21

**Comment by nwwells** [comment]
I will try it out and close this issue if successful

**Comment by nwwells** [comment]
Just added joshgordon/wscat#1 to allow the specification of a passphrase, as an amendment to #21. Assuming @joshgordon accepts that PR, that would resolve my issue.

**Comment by nwwells** [comment]
Thanks!
