### ISSUE TITLE
unsupported protocol version (again)

### ISSUE THREAD

**Issue by simonklb** [websockets/wscat#27]
https://github.com/websockets/wscat/commit/00e9a396e19b412fd99fd0a63862d52d007cc141 re-introduced https://github.com/websockets/ws/issues/612 by overwriting the fix in https://github.com/websockets/wscat/commit/4de45ae56f817a37af5a2a689b7e1c59f748e441

**Comment by lpinca** [comment]
Good catch, can you please send a PR?
Thanks.

**Comment by lpinca** [comment]
Fixed again in 58b9b6bd4322ac11bfa44fb3fb483396c641c55d.
Thanks for reporting.
