### ISSUE TITLE
release 2.0.0

### ISSUE THREAD

**Issue by nwwells** [websockets/wscat#35]
@lpinca, @3rd-Eden, @einaros... I don't have access on npm to publish this package, but I made some changes that will fix a few issues. Can you please release `1.2.0` or give me access to?

**Comment by lpinca** [comment]
@nwwells https://github.com/websockets/wscat/pull/34 is a breaking change so it must be a major (2.0.0).

**Comment by lpinca** [comment]
Let me know if you want to add more breaking changes like using ES6 features where possible before releasing 2.0.0 or you are good as is.

**Comment by nwwells** [comment]
How is it breaking? the command line API stays the same, no?

**Comment by lpinca** [comment]
ws@2 only works on Node.js 4.5.0 or greater.

**Comment by nwwells** [comment]
fixed in c6dfcf8

**Comment by lpinca** [comment]
@nwwells ok I'll cut the release later or tomorrow. Please never bump the package.json version as we use a dedicated commit for the release like https://github.com/websockets/wscat/commit/b6828075af3e01556bf07d4d46d95213bb51a7f9.

**Comment by nwwells** [comment]
Understood.
