### ISSUE TITLE
wscat Sends different GET Header through Proxy

### ISSUE THREAD

**Issue by c0yote** [websockets/wscat#42]
I'm calling wscat against two different ports:

Simple node.js WebSocket Server:
    `wscat --connect ws://uri:8000`

NGINX Proxy:
    `wscat --connect ws://uri:80`

`tcpdump` shows the following:

The header in the GET to the node server includes:
```
Connection: Upgrade
Upgrade: websocket
```

The header in the GET to the NGINX server only has:
```
Connection: keep-alive
```

Why would this happen?

**Comment by lpinca** [comment]
I don't know, the request is always the same: https://github.com/websockets/ws/blob/cb1c893ce94f3d800cd6e4166e6640bda24d74ab/lib/WebSocket.js#L636.

**Comment by c0yote** [comment]
I finally figured out that my companies firewall was stripping out the Upgrade on port 80 and only port 80.  FML...

Thanks.
