### ISSUE TITLE
cursor jump to the beginning of the line

### ISSUE THREAD

**Issue by zhanglongqi** [websockets/wscat#46]
If the server side keep pushing message to the client then the input cursor will jump to the beginning as soon as the new message arrive.

**Comment by VaidotasSm** [comment]
Encountered this issue today - tried to use `wscat` for quick websocket testing, however it is not usable for two way communication if server feeds messages rather fast - you just cannot type quickly enough.

**Comment by lpinca** [comment]
Should be fixed by #123.
