### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by jeduden** [websockets/wscat#54]
is there a way to configure an http proxy with wscat's cli ?

**Comment by nwwells** [comment]
Not currently. I'm not exactly sure what you're looking for, though. What's your use case?

**Comment by jeduden** [comment]
to configure corperate proxies explicitly

**Comment by nwwells** [comment]
Oh I think 8 understand what you mean. No, this isn't currently supported,
and I'm not sure what can be done to support it.

**Comment by jeduden** [comment]
An integration of this lib would be needed: https://github.com/TooTallNate/node-https-proxy-agent

**Comment by odilitime** [comment]
nginx can proxy websockets
https://www.nginx.com/blog/websocket-nginx/
