### ISSUE TITLE
Solved - Problem connecting with SocketCluster.io

### ISSUE THREAD

**Issue by MadGeometer** [websockets/wscat#62]
Solved - connect to ws://localhost:xxxx/socketcluster/

When attempting to connect to SocketCluster.io running on localhost, a 400 is returned.
Example:
wscat -c ws://127.0.0.1:8000
error: Error: unexpected server response (400)

Not sure if this is a problem with wscat or SC!

**Comment by MadGeometer** [comment]
Thanks, Ipinca, got it to work. Problem was the connection URL, it should be
ws://localhost:xxxx/socketcluster/
and not 
ws://localhost:xxxx

**Comment by mdedirudianto** [comment]
I also found another thing, just in case someone get the same problem

It should be:
ws://localhost:xxxx/socketcluster/
and not
ws://localhost:xxxx/socketcluster

Don't forget to put backslash ('/') at then end

**Comment by RossSihovsk** [comment]
i started my websocket server and trying to connect with this
wscat -c ws://localhost:8090/socket/ 
but it doesn't work. I get error: Unexpected server response: 400
