### ISSUE TITLE
NPM Github link is incorrect

### ISSUE THREAD

**Issue by woverton** [websockets/wscat#9]
On the npm page https://www.npmjs.com/package/wscat the github link does not link to this repo.

This could be fixed by simply doing an npm release if i'm not mistaken?

Would help get a little more traction for the repo :)

**Comment by 3rd-Eden** [comment]
Done, published 1.0.1 -- Also updated the `ws` dependency to latest version.

**Comment by woverton** [comment]
Awesome, thanks :)
