### ISSUE TITLE
Error when passing multiple query string params

### ISSUE THREAD

**Issue by stevecreswick** [websockets/wscat#93]
I was trying to connect to a websocket using wscat and passing params through the query string.  When passing one parameter, this worked successfully.  But when trying to pass multiple parameters a connection request was never sent to the websocket.

This worked: `wss://websocketurl.com?some_id=1234`

This did not work: `wss://websocketurl.com?some_id=1234&another_id=5678`

Trying to pass multiple params in the query string printed out the following to the console on each subsequent attempt.  

```
[1] 96022
[2] 96063
[3] 96070
[4] 97671
[5] 97674
```

This looks like maybe an incrementing id coming from wscat and a process id?

I'm not quite sure why that second query param is causing it to not attempt a connection.

Thanks for any help!

**Comment by lpinca** [comment]
Wrap the in URL in double quotes like this:

```
wscat -c "wss://websocketurl.com?some_id=1234&another_id=5678"
```

**Comment by stevecreswick** [comment]
That worked.  Thanks!
