### ISSUE TITLE
wss with self signed cert not working

### ISSUE THREAD

**Issue by SephVelut** [websockets/wscat#95]
`wscat --key server.key.pem --cert server.pem -c wss://127.0.0.1:8080` results in

`(node:56311) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.
error: self signed certificate`

**Comment by lpinca** [comment]
Use the `--no-check` option it should work.

**Comment by lpinca** [comment]
The certificate in the issue description was self signed as per error message.

**Comment by developer992** [comment]
Hello, which version was this added in?

i have 5.2.0
```
root@06c7348e797a:/app# wscat -V
5.2.0
```

```
> root@06c7348e797a:/app# wscat -c --no-check "wss://host.docker.internal:443"
error: getaddrinfo ENOTFOUND --no-check
```

**Comment by MartinKunft** [comment]
> Hello, which version was this added in?
> 
> i have 5.2.0
> 
> ```
> root@06c7348e797a:/app# wscat -V
> 5.2.0
> ```
> 
> ```
> > root@06c7348e797a:/app# wscat -c --no-check "wss://host.docker.internal:443"
> error: getaddrinfo ENOTFOUND --no-check
> ```

-c expects a url parameter try wscat --no-check -c "wss://host.docker.internal:443"
